### Softmax function

In [1]:
import numpy as np
import math

In [2]:
def OneHotEncode(y):
    shape=(y.shape[1], y.max()+1)
    OHE = np.zeros(shape)
    rows = np.arange(y.shape[1])
    OHE[rows, y]=1
    
    return OHE.T

In [3]:
Z = np.array([[1,2,3,5,2],
              [2,2,4,2,1],
              [4,6,2,1,1]])

Z = Z.T
print(Z)

[[1 2 4]
 [2 2 6]
 [3 4 2]
 [5 2 1]
 [2 1 1]]


In [4]:
def softmax(Z):
    if Z.shape[0] < Z.shape[1]:
        Z = Z.T
    
    exps = np.exp(Z-Z.max())
    sums = np.sum(exps, axis=1, keepdims=True)
    return exps/sums

In [6]:
Y = np.array([1,2,2,1,1])
Y = Y.reshape(1, len(Y))
Y = OneHotEncode(Y)

In [9]:
Y.T

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [10]:
softmax(Z)

array([[0.04201007, 0.1141952 , 0.84379473],
       [0.01766842, 0.01766842, 0.96466316],
       [0.24472847, 0.66524096, 0.09003057],
       [0.93623955, 0.04661262, 0.01714783],
       [0.57611688, 0.21194156, 0.21194156]])

In [11]:
diff = Y.T - softmax(Z)

In [12]:
diff

array([[-0.04201007,  0.8858048 , -0.84379473],
       [-0.01766842, -0.01766842,  0.03533684],
       [-0.24472847, -0.66524096,  0.90996943],
       [-0.93623955,  0.95338738, -0.01714783],
       [-0.57611688,  0.78805844, -0.21194156]])