In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 


In [6]:
m = 10
x = np.random.randn(m, 1)
w = np.random.randn(1,1)

print(x.shape)
print(w.shape)
print(len(x))

(10, 1)
(1, 1)
10


In [4]:
if x.shape != (1,m):
    x = x.reshape(1, m)

In [5]:
x.shape

(1, 10)

In [24]:
import numpy as np
from numpy.core.fromnumeric import shape
import pandas as pd
import matplotlib.pyplot as plt

class LinearRegression:
    def __init__(self, X, y):
        if X.shape != (1,len(X)):
            self.X = X.T
            self.y = y.T
        else:
            self.X = X
            self.y = y

        self.W = np.random.randn(1,1)
        self.b = np.zeros(shape=(1,1))
        self.predictions = 0
        self.loss = 0
    
    def predict(self):
        m = len(self.X)
        self.predictions = np.dot(self.W, self.X) + self.b
        return self.predictions
    
    def MSE(self):
        m = len(self.X)
        mse = 1/(2*m) * (np.sum((self.y-self.predictions), axis=1, keepdims=True))
        self.loss = mse
        return self.loss

In [25]:
X = np.random.randn(100,1)
y = np.random.randint(2, size=(100,1))

In [26]:
slr = LinearRegression(X, y)

In [27]:
pred = slr.predict()

In [29]:
slr.MSE()

array([[22.28467348]])

In [30]:
slr.loss

array([[22.28467348]])

In [34]:
(slr.b * X.T).shape

(1, 100)

In [38]:
np.dot((slr.W), X.T ** 2).shape

(1, 100)

In [39]:
(X.T ** 2).shape

(1, 100)

In [45]:
(np.sum(((slr.X*slr.y) - np.dot(slr.W, slr.X**2) + slr.b * slr.X), axis=1, keepdims=True)).shape

(1, 1)

In [46]:
(np.sum((slr.y - (np.dot(slr.W, slr.X) + slr.b)), axis=1, keepdims=True))

array([[44.56934697]])

In [ ]:
        m = len(self.X)
        X_bar = 1/m * (np.sum(self.X, axis=1, keepdims=True))
        y_bar = 1/m * (np.sum(self.y, axis=1, keepdims=True))

        numerator = (X_bar * y_bar) - (1/m * np.sum(self.y * self.X, axis = 1, keepdims=True))
        denominator = (self.X ** 2) - (1/m * np.sum(self.X ** 2, axis=1, keepdims=True))

        W_opt = np.divide(numerator, denominator)
        b_opt = y_bar - (W_opt * X_bar)

        loss_opt = 1/m * (np.sum(self.y - (np.dot(W_opt, self.X) + b_opt), axis=1, keepdims=True))
        return loss_opt

In [48]:
X = X.T
y = y.T

print(X.shape)
print(y.shape)

(1, 100)
(1, 100)


In [49]:
m = len(X)
x_bar = 1/m * (np.sum(X, axis=1, keepdims=True))
y_bar = 1/m * (np.sum(y, axis=1, keepdims=True))

print(x_bar.shape)
print(y_bar.shape)

(1, 1)
(1, 1)


In [52]:
numerator = (x_bar * y_bar) - (1/m * np.sum(y * X, axis = 1, keepdims=True))
denominator = (x_bar ** 2) - (1/m * np.sum(X ** 2, axis=1, keepdims=True))

print(numerator.shape)
print(denominator.shape)

(1, 1)
(1, 1)


In [54]:
np.divide(numerator, denominator).shape

(1, 1)